version: '3.1'

services:
  motioncanvas:
    build:
      context: ./docker/
#     dockerfile: Dockerfile.flowise
    image: motioncanvas
    network_mode: "host"
    pid: "host"
    container_name: mc
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./projects/:/projects/
    command: sleep infinity
    working_dir: /projects/

#   command: npm run serve

#   command: /bin/sh -c "sleep 3; flowise start"
#    # nur wirksam auf ionos2 mit traefik:

