version: '3.1'

services:
  motioncanvas:
    build:
      context: ./docker/
    image: motioncanvas
    network_mode: "host"
    pid: "host"
    container_name: mc
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./projects/:/projects/
    command: sleep infinity
    working_dir: /projects/

#   command: npm run serve


  nginx:
    image: nginx:latest
    container_name: nginx
    network_mode: "host"
#   ports:
#     - 8080:80
    volumes: 
      - ./images:/usr/share/nginx/html:ro
      - ./docker/nginx.conf/:/etc/nginx/nginx.conf:ro

